# Generated by Django 5.1.4 on 2024-12-27 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetBehaviorWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('days', models.ManyToManyField(related_name='target_behaviors', to='target_behaviors.day')),
                ('periods', models.ManyToManyField(related_name='target_behaviors', to='target_behaviors.period')),
            ],
        ),
        migrations.CreateModel(
            name='TargetBehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(choices=[(0, 'Did Not Achieve Goal'), (1, 'Warning Given'), (2, 'Achieved Goal')])),
                ('notes', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='target_behaviors.day')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='target_behaviors.period')),
                ('target_behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='target_behaviors.targetbehavior')),
            ],
        ),
    ]
