# Generated by Django 5.1.4 on 2025-01-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("target_behaviors", "0003_basic_values"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetbehavior",
            options={"verbose_name": "goal", "verbose_name_plural": "goals"},
        ),
    ]
